### ISSUE TITLE
Error in query.rs

### ISSUE THREAD

**Issue by STPR** [evaneaston/openweathermap#8]
Hello,
Thanks for this library 👍

There's an error in the query.rs file:
https://github.com/evaneaston/openweathermap/blob/f5fe87144b377f7ab21bdfeea2a4f69cb492a492/client/src/query.rs#L20
Must be:
```rust
vec![("lat", self.lat.to_string()), ("lon", self.lon.to_string())]
```

**Comment by evaneaston** [comment]
You are right.  I clearly don't rely on that variant, or have a test.

**Comment by evaneaston** [comment]
@STPR thanks for the bug report.  I've published a fix for you.
